-- =============================================================
-- GOMAS LAB V2 — TIER 1: ZERO PERSISTENCE ARCHITECTURE
-- =============================================================
--
-- Decisión de arquitectura: La aplicación es de CONVERSIÓN,
-- no de almacenamiento. El usuario sube un PDF, se convierte
-- a Markdown vía Gemini VLM, descarga el resultado, y fin.
--
-- No se persisten documentos de usuarios en base de datos.
-- No hay tablas de users, documents, ni markdown_output.
--
-- Flujo: Upload → Gemini OCR → Markdown → Download → Fin
--
-- Futuro (post-MVP):
--   - Auth + user sessions (si se necesita billing/Stripe)
--   - Processing logs para métricas y debugging
--   - Rate limiting con almacenamiento temporal
--
-- Este archivo se mantiene como referencia de arquitectura.
-- =============================================================
